"""
Block classifier: maps each process step to its block in the process grammar,
and determines valid next steps based on block structure.

The backbone order is fixed:
  PREFIX → INITIAL_MEASUREMENTS → PRE_PROCESS_CLEAN → FAMILY_PREP →
  FIRST_OXIDATION → PROCESS_CYCLES → ILD_BLOCK → VIA_BLOCK →
  METAL_BLOCK → PASSIVATION_BLOCK → BACKSIDE_BLOCK →
  FINAL_INSPECTION → TEST_SUITE → SUFFIX
"""

# Map every step to its block
STEP_TO_BLOCK = {
    # PREFIX
    "RECEIVE WAFER LOT": "PREFIX",
    "LOT IDENTIFICATION": "PREFIX",
    "INITIAL WAFER INSPECTION": "PREFIX",
    "PRE CLEAN INSPECTION": "PREFIX",

    # INITIAL_MEASUREMENTS
    "MEASURE THICKNESS": "INITIAL_MEASUREMENTS",
    "MEASURE INITIAL THICKNESS": "INITIAL_MEASUREMENTS",
    "MEASURE INITIAL GEOMETRY": "INITIAL_MEASUREMENTS",
    "MEASURE SURFACE PARTICLES": "INITIAL_MEASUREMENTS",
    "MEASURE SURFACE DEFECTS": "INITIAL_MEASUREMENTS",

    # PRE_PROCESS_CLEAN
    "PRE CLEAN WAFER": "PRE_PROCESS_CLEAN",
    "WAFER CLEAN PRE PROCESS": "PRE_PROCESS_CLEAN",
    "BACKSIDE CLEAN": "PRE_PROCESS_CLEAN",  # also in BACKSIDE_BLOCK
    "FRONTSIDE CLEAN": "PRE_PROCESS_CLEAN",
    "WET CLEAN RCA1": "PRE_PROCESS_CLEAN",
    "RCA CLEAN 1": "PRE_PROCESS_CLEAN",
    "WET CLEAN RCA2": "PRE_PROCESS_CLEAN",
    "RCA CLEAN 2": "PRE_PROCESS_CLEAN",
    "HF DIP": "PRE_PROCESS_CLEAN",
    "DRY WAFER": "PRE_PROCESS_CLEAN",
    "DRY WAFER BACKSIDE": "PRE_PROCESS_CLEAN",

    # FAMILY_PREP (MOSFET)
    "SUBSTRATE CHECK": "FAMILY_PREP",
    "EPITAXY PREP": "FAMILY_PREP",
    "EPITAXIAL DEPOSITION": "FAMILY_PREP",
    "MEASURE EPITAXY THICKNESS": "FAMILY_PREP",
    "MEASURE RESISTIVITY": "FAMILY_PREP",
    "EPITAXY ANNEAL": "FAMILY_PREP",
    "WAFER SURFACE CLEAN": "FAMILY_PREP",
    # FAMILY_PREP (IGBT)
    "EPITAXIAL WAFER CHECK": "FAMILY_PREP",
    "EPITAXIAL REWORK CHECK": "FAMILY_PREP",
    "EPITAXIAL LAYER PREP": "FAMILY_PREP",
    # FAMILY_PREP (IC)
    "WAFER CLEAN PRE-GRIND": "FAMILY_PREP",
    "GRINDING WAFER BACKSIDE": "FAMILY_PREP",
    "MEASURE GEOMETRY": "FAMILY_PREP",
    "ETCH WET BACKSIDE": "FAMILY_PREP",
    "RINSE WET WAFER_EDGE": "FAMILY_PREP",
    "MEASURE BACKSIDE ROUGHNESS": "FAMILY_PREP",

    # FIRST_OXIDATION
    "THERMAL OXIDATION": "FIRST_OXIDATION",
    "GATE OXIDE PREP": "FIRST_OXIDATION",
    "GATE OXIDE GROWTH": "FIRST_OXIDATION",
    "MEASURE OXIDE THICKNESS": "FIRST_OXIDATION",
    "SURFACE PREP FOR DEPOSITION": "FIRST_OXIDATION",
    "DEPOSIT PAD OXIDE": "FIRST_OXIDATION",
    "ANNEAL OXIDE": "FIRST_OXIDATION",
    "OXIDE STRIP": "FIRST_OXIDATION",
    "MEASURE FILM THICKNESS": "FIRST_OXIDATION",  # context-dependent

    # PROCESS_CYCLES (litho + etch + implant)
    "SPIN COAT PHOTORESIST": "PROCESS_CYCLES",
    "SOFT BAKE": "PROCESS_CYCLES",
    "POST EXPOSE BAKE": "PROCESS_CYCLES",
    "DEVELOP PHOTORESIST": "PROCESS_CYCLES",
    "HARD BAKE": "PROCESS_CYCLES",
    "OXIDE ETCH": "PROCESS_CYCLES",
    "OXIDE ETCH DRY": "PROCESS_CYCLES",
    "POLYSILICON ETCH": "PROCESS_CYCLES",
    "POLYSILICON ETCH DRY": "PROCESS_CYCLES",
    "STRIP PHOTORESIST": "PROCESS_CYCLES",
    "STRIP RESIST": "PROCESS_CYCLES",
    "STRIP RESIST LEVEL 2": "PROCESS_CYCLES",
    "CLEAN AFTER ETCH": "PROCESS_CYCLES",
    "CLEAN AFTER OXIDE ETCH": "PROCESS_CYCLES",
    "CLEAN AFTER POLY ETCH": "PROCESS_CYCLES",
    "CLEAN AFTER WINDOW ETCH": "PROCESS_CYCLES",
    "CLEAN AFTER FIELD ETCH": "PROCESS_CYCLES",
    "IMPLANT WELL": "PROCESS_CYCLES",
    "IMPLANT SOURCE DRAIN": "PROCESS_CYCLES",
    "IMPLANT SOURCE REGION": "PROCESS_CYCLES",
    "IMPLANT LDD": "PROCESS_CYCLES",
    "IMPLANT P BODY": "PROCESS_CYCLES",
    "IMPLANT N BUFFER": "PROCESS_CYCLES",
    "IMPLANT CHANNEL STOP": "PROCESS_CYCLES",
    "IMPLANT DRAIN / CATHODE REGION": "PROCESS_CYCLES",
    "IMPLANT N-TYPE": "PROCESS_CYCLES",
    "DRIVE IN DIFFUSION": "PROCESS_CYCLES",
    "RAPID THERMAL ANNEAL": "PROCESS_CYCLES",
    "LIGHT ANNEAL": "PROCESS_CYCLES",
    "PRE ANNEAL CHECK": "PROCESS_CYCLES",
    "DEPOSIT POLYSILICON": "PROCESS_CYCLES",
    "POLYSILICON ANNEAL": "PROCESS_CYCLES",
    "ANNEAL POLYSILICON": "PROCESS_CYCLES",
    "DEPOSIT SPACER DIELECTRIC": "PROCESS_CYCLES",
    "ANISOTROPIC ETCH SPACER": "PROCESS_CYCLES",
    "DEPOSIT FIELD OXIDE": "PROCESS_CYCLES",
    "DENSIFY OXIDE": "PROCESS_CYCLES",
    "DEPOSIT GATE OXIDE OR DIELECTRIC": "PROCESS_CYCLES",
    "ANNEAL DIELECTRIC": "PROCESS_CYCLES",
    "ETCH SILICON OR OXIDE WINDOW": "PROCESS_CYCLES",
    "FIELD OXIDE ETCH": "PROCESS_CYCLES",
    # Measurements within cycles
    "MEASURE OPENING CD": "PROCESS_CYCLES",
    "MEASURE JUNCTION DEPTH": "PROCESS_CYCLES",
    "MEASURE GATE OXIDE THICKNESS": "PROCESS_CYCLES",
    "MEASURE POLY THICKNESS": "PROCESS_CYCLES",
    "MEASURE GATE CD": "PROCESS_CYCLES",
    "MEASURE SHEET RESISTANCE": "PROCESS_CYCLES",
    "MEASURE SPACER WIDTH": "PROCESS_CYCLES",
    "MEASURE JUNCTION PROFILE": "PROCESS_CYCLES",
    "MEASURE WINDOW CD": "PROCESS_CYCLES",
    "MEASURE SURFACE UNIFORMITY": "PROCESS_CYCLES",
    "MEASURE OXIDE QUALITY": "PROCESS_CYCLES",
    "MEASURE DEVICE PARAMETER": "PROCESS_CYCLES",
    "MEASURE CD LEVEL 1": "PROCESS_CYCLES",
    "MEASURE CD LEVEL 2": "PROCESS_CYCLES",
    # Pattern inspections
    "INSPECT PATTERN LEVEL 1": "PROCESS_CYCLES",
    "PATTERN INSPECTION LEVEL 1": "PROCESS_CYCLES",
    "INSPECT PATTERN LEVEL 2": "PROCESS_CYCLES",
    "PATTERN INSPECTION LEVEL 2": "PROCESS_CYCLES",
    "POLY PATTERN INSPECTION": "PROCESS_CYCLES",
    "P BODY WINDOW INSPECTION": "PROCESS_CYCLES",
    "FIELD PATTERN INSPECTION": "PROCESS_CYCLES",
    # Align/expose (level-dependent)
    **{f"ALIGN MASK LEVEL {i}": "PROCESS_CYCLES" for i in range(1, 7)},
    **{f"EXPOSE LITHO LEVEL {i}": "PROCESS_CYCLES" for i in range(1, 7)},

    # ILD_BLOCK
    "DEPOSIT INTERLAYER DIELECTRIC": "ILD_BLOCK",
    "DEPOSIT INTERLEVEL DIELECTRIC": "ILD_BLOCK",
    "DENSIFY DIELECTRIC": "ILD_BLOCK",
    "MEASURE DIELECTRIC THICKNESS": "ILD_BLOCK",
    "CMP DIELECTRIC": "ILD_BLOCK",
    "CMP INTERLAYER DIELECTRIC": "ILD_BLOCK",
    "MEASURE PLANARITY": "ILD_BLOCK",
    "MEASURE SURFACE PLANARITY": "ILD_BLOCK",

    # VIA_BLOCK
    "VIA ETCH": "VIA_BLOCK",
    "VIA ETCH THROUGH DIELECTRIC": "VIA_BLOCK",
    "DIELECTRIC ETCH VIA": "VIA_BLOCK",
    "VIA INSPECTION": "VIA_BLOCK",
    "VIA OPENING INSPECTION": "VIA_BLOCK",
    "CLEAN AFTER VIA ETCH": "VIA_BLOCK",
    "MEASURE VIA CD": "VIA_BLOCK",
    "DEPOSIT BARRIER METAL": "VIA_BLOCK",
    "DEPOSIT METAL SEED": "VIA_BLOCK",
    "DEPOSIT TUNGSTEN SEED": "VIA_BLOCK",
    "FILL VIA METAL": "VIA_BLOCK",
    "FILL VIA TUNGSTEN": "VIA_BLOCK",
    "CMP METAL": "VIA_BLOCK",
    "CMP VIA FILL": "VIA_BLOCK",
    "MEASURE CONTACT RESISTANCE": "VIA_BLOCK",
    "MEASURE VIA RESISTANCE": "VIA_BLOCK",

    # METAL_BLOCK
    "DEPOSIT METAL 1": "METAL_BLOCK",
    "DEPOSIT TOP METAL": "METAL_BLOCK",
    "ANNEAL METAL 1": "METAL_BLOCK",
    "ANNEAL METAL": "METAL_BLOCK",
    "MEASURE METAL THICKNESS": "METAL_BLOCK",
    "METAL PATTERN INSPECTION": "METAL_BLOCK",
    "METAL ETCH": "METAL_BLOCK",
    "METAL ETCH DRY": "METAL_BLOCK",
    "CLEAN AFTER METAL ETCH": "METAL_BLOCK",
    "MEASURE LINE WIDTH": "METAL_BLOCK",

    # PASSIVATION_BLOCK
    "DEPOSIT PASSIVATION": "PASSIVATION_BLOCK",
    "DEPOSIT PASSIVATION LAYER": "PASSIVATION_BLOCK",
    "CURE PASSIVATION": "PASSIVATION_BLOCK",
    "MEASURE PASSIVATION THICKNESS": "PASSIVATION_BLOCK",
    "MEASURE PASSIVATION QUALITY": "PASSIVATION_BLOCK",
    "OPEN PAD WINDOW": "PASSIVATION_BLOCK",
    "OPEN BOND PAD WINDOW": "PASSIVATION_BLOCK",
    "PAD WINDOW LITHO": "PASSIVATION_BLOCK",
    "OPEN PAD WINDOW LITHO": "PASSIVATION_BLOCK",
    "DEVELOP PAD WINDOW": "PASSIVATION_BLOCK",
    "PASSIVATION ETCH PAD OPENING": "PASSIVATION_BLOCK",
    "PASSIVATION ETCH": "PASSIVATION_BLOCK",
    "CLEAN PAD OPENING": "PASSIVATION_BLOCK",
    "MEASURE PAD OPENING": "PASSIVATION_BLOCK",

    # BACKSIDE_BLOCK
    "BACKSIDE THINNING CHECK": "BACKSIDE_BLOCK",
    "BACKSIDE CLEAN FINAL": "BACKSIDE_BLOCK",
    "DEPOSIT BACKSIDE PROTECTION": "BACKSIDE_BLOCK",
    "BACKSIDE GRIND": "BACKSIDE_BLOCK",
    "MEASURE WAFER THICKNESS": "BACKSIDE_BLOCK",
    "BACKSIDE ETCH CLEAN": "BACKSIDE_BLOCK",
    "BACKSIDE RINSE": "BACKSIDE_BLOCK",
    "BACKSIDE DRY": "BACKSIDE_BLOCK",
    "BACKSIDE METALLIZATION PREP": "BACKSIDE_BLOCK",
    "DEPOSIT BACKSIDE METAL": "BACKSIDE_BLOCK",
    "BACKSIDE ANNEAL": "BACKSIDE_BLOCK",
    "MEASURE BACKSIDE CONTACT": "BACKSIDE_BLOCK",

    # FINAL_INSPECTION
    "FINAL CLEAN": "FINAL_INSPECTION",
    "FINAL THICKNESS MEASURE": "FINAL_INSPECTION",
    "FINAL GEOMETRY CHECK": "FINAL_INSPECTION",
    "FINAL OXIDE CHECK": "FINAL_INSPECTION",
    "FINAL CD INSPECTION": "FINAL_INSPECTION",
    "FINAL PARTICLE INSPECTION": "FINAL_INSPECTION",
    "FRONTSIDE CLEAN FINAL": "FINAL_INSPECTION",
    "FINAL ELECTRICAL TEST PREP": "FINAL_INSPECTION",

    # TEST_SUITE
    "PARAMETRIC TEST": "TEST_SUITE",
    "ELECTRICAL PARAMETRIC TEST": "TEST_SUITE",
    "LEAKAGE TEST": "TEST_SUITE",
    "THRESHOLD VOLTAGE TEST": "TEST_SUITE",
    "BREAKDOWN VOLTAGE TEST": "TEST_SUITE",
    "SWITCHING TEST": "TEST_SUITE",
    "WAFER SORT TEST": "TEST_SUITE",
    "YIELD ANALYSIS": "TEST_SUITE",

    # SUFFIX
    "LOT RELEASE": "SUFFIX",
    "FINAL LOT RELEASE": "SUFFIX",
    "PACKAGE PREPARATION": "SUFFIX",
    "SHIP LOT": "SUFFIX",
}

# Ordered block sequence (the backbone)
BLOCK_ORDER = [
    "PREFIX",
    "INITIAL_MEASUREMENTS",
    "PRE_PROCESS_CLEAN",
    "FAMILY_PREP",
    "FIRST_OXIDATION",
    "PROCESS_CYCLES",
    "ILD_BLOCK",
    "VIA_BLOCK",
    "METAL_BLOCK",
    "PASSIVATION_BLOCK",
    "BACKSIDE_BLOCK",
    "FINAL_INSPECTION",
    "TEST_SUITE",
    "SUFFIX",
]

BLOCK_TO_ID = {b: i for i, b in enumerate(BLOCK_ORDER)}
NUM_BLOCKS = len(BLOCK_ORDER)


def classify_step_block(step: str) -> str:
    """Map a step name to its block. Returns 'UNKNOWN' if not found."""
    return STEP_TO_BLOCK.get(step, "UNKNOWN")


def classify_step_block_id(step: str) -> int:
    """Map a step name to its block ID (0-13). Returns -1 if unknown."""
    block = STEP_TO_BLOCK.get(step)
    if block is None:
        return -1
    return BLOCK_TO_ID.get(block, -1)


def get_current_block(steps: list[str]) -> str:
    """Determine the current block from a sequence of steps."""
    if not steps:
        return "PREFIX"
    # Use the last step's block
    return classify_step_block(steps[-1])


def get_current_block_id(steps: list[str]) -> int:
    """Determine the current block ID from a sequence."""
    block = get_current_block(steps)
    return BLOCK_TO_ID.get(block, -1)


def get_valid_next_blocks(current_block: str) -> list[str]:
    """
    Given the current block, return which blocks the next step could belong to.
    Rules: stay in current block OR move to the next block in order.
    Special: PROCESS_CYCLES can also go back to itself (multiple cycles).
    """
    if current_block not in BLOCK_TO_ID:
        return BLOCK_ORDER  # unknown → allow anything

    idx = BLOCK_TO_ID[current_block]
    valid = [current_block]  # can stay in current block

    # Can move to next block
    if idx + 1 < len(BLOCK_ORDER):
        valid.append(BLOCK_ORDER[idx + 1])

    # PROCESS_CYCLES includes litho for VIA and METAL (they share SPIN COAT etc)
    # So from PROCESS_CYCLES we can also jump to ILD_BLOCK
    if current_block == "PROCESS_CYCLES" and idx + 2 < len(BLOCK_ORDER):
        valid.append(BLOCK_ORDER[idx + 2])  # ILD_BLOCK

    return valid


def get_valid_next_steps_by_block(steps: list[str]) -> set[str]:
    """
    Given the sequence so far, return the set of step names that are valid
    based on block structure.
    """
    current_block = get_current_block(steps)
    valid_blocks = get_valid_next_blocks(current_block)

    valid_steps = set()
    for step, block in STEP_TO_BLOCK.items():
        if block in valid_blocks:
            valid_steps.add(step)

    return valid_steps
