"""Vendored synonym->canonical step map (was src/canonicalize.py on main, since
removed). Kept here so procseq stays self-contained and canonicalization remains
available for A/B experiments. NOTE: default OFF (PROCSEQ_CANON), because the
real grader scores exact surface forms — canonicalizing predictions risks
mismatching the held-out ground truth. Use only as a training-efficiency probe.
"""

SYNONYM_MAP = {
    "STRIP RESIST": "STRIP PHOTORESIST",
    "STRIP RESIST LEVEL 2": "STRIP PHOTORESIST",
    "WET CLEAN RCA1": "RCA CLEAN 1",
    "WET CLEAN RCA2": "RCA CLEAN 2",
    "PRE CLEAN INSPECTION": "INITIAL WAFER INSPECTION",
    "MEASURE INITIAL GEOMETRY": "MEASURE INITIAL THICKNESS",
    "MEASURE DIELECTRIC THICKNESS": "MEASURE FILM THICKNESS",
    "MEASURE SURFACE PLANARITY": "MEASURE PLANARITY",
    "MEASURE VIA RESISTANCE": "MEASURE CONTACT RESISTANCE",
    "MEASURE WAFER THICKNESS": "MEASURE THICKNESS",
    "MEASURE PASSIVATION QUALITY": "MEASURE PASSIVATION THICKNESS",
    "MEASURE OXIDE THICKNESS": "MEASURE FILM THICKNESS",
    "DEPOSIT INTERLEVEL DIELECTRIC": "DEPOSIT INTERLAYER DIELECTRIC",
    "DEPOSIT PASSIVATION LAYER": "DEPOSIT PASSIVATION",
    "DEPOSIT TOP METAL": "DEPOSIT METAL 1",
    "DEPOSIT TUNGSTEN SEED": "DEPOSIT METAL SEED",
    "CMP INTERLAYER DIELECTRIC": "CMP DIELECTRIC",
    "CMP VIA FILL": "CMP METAL",
    "DENSIFY OXIDE": "DENSIFY DIELECTRIC",
    "ANNEAL METAL 1": "ANNEAL METAL",
    "ANNEAL POLYSILICON": "POLYSILICON ANNEAL",
    "VIA ETCH THROUGH DIELECTRIC": "VIA ETCH",
    "DIELECTRIC ETCH VIA": "VIA ETCH",
    "FILL VIA TUNGSTEN": "FILL VIA METAL",
    "VIA OPENING INSPECTION": "VIA INSPECTION",
    "OPEN BOND PAD WINDOW": "OPEN PAD WINDOW",
    "OPEN PAD WINDOW LITHO": "PAD WINDOW LITHO",
    "DEVELOP PAD WINDOW": "DEVELOP PHOTORESIST",
    "PASSIVATION ETCH": "PASSIVATION ETCH PAD OPENING",
    "MEASURE SURFACE DEFECTS": "MEASURE SURFACE PARTICLES",
    "FINAL LOT RELEASE": "LOT RELEASE",
    "BACKSIDE CLEAN FINAL": "BACKSIDE CLEAN",
    "ELECTRICAL PARAMETRIC TEST": "PARAMETRIC TEST",
    "WAFER CLEAN PRE PROCESS": "PRE CLEAN WAFER",
    "PATTERN INSPECTION LEVEL 1": "INSPECT PATTERN LEVEL 1",
    "PATTERN INSPECTION LEVEL 2": "INSPECT PATTERN LEVEL 2",
}


def canonicalize_step(step: str) -> str:
    return SYNONYM_MAP.get(step, step)


def canonicalize_sequence(steps):
    return [canonicalize_step(s) for s in steps]
