export const STEP_DESCRIPTIONS: Record<string, string> = {
  'RECEIVE WAFER LOT': 'Receive the incoming wafer lot, verify lot ID, product code, and route version.',
  'LOT IDENTIFICATION': 'Check wafer count, carrier ID, and traveler against the manufacturing order.',
  'INITIAL WAFER INSPECTION': 'Inspect wafers for visible defects, edge chips, handling damage, and contamination.',
  'MEASURE THICKNESS': 'Measure starting wafer thickness at center and edge locations.',
  'MEASURE SURFACE PARTICLES': 'Perform particle scan to quantify surface contamination before processing.',
  'PRE CLEAN WAFER': 'Remove loose particles and organic residues prior to wet processing.',
  'RCA CLEAN 1': 'Apply alkaline clean to remove organic contamination; monitor temperature and timing.',
  'RCA CLEAN 2': 'Apply acidic clean to remove metallic residues and remaining contaminants.',
  'HF DIP': 'Remove native oxide with dilute HF and prepare a hydrogen-terminated surface.',
  'DRY WAFER': 'Dry wafers using spin-rinse-dry or nitrogen drying to avoid water marks.',
  'SUBSTRATE CHECK': 'Verify substrate orientation, resistivity, and incoming material specification.',
  'THERMAL OXIDATION': 'Grow a thin silicon oxide layer; control temperature, time, and target thickness.',
  'MEASURE OXIDE THICKNESS': 'Verify oxide thickness and uniformity with metrology.',
  'SPIN COAT PHOTORESIST': 'Apply photoresist; track spin speed, resist thickness, and coating quality.',
  'SOFT BAKE': 'Remove solvent from the resist film and stabilize it for lithography.',
  'ALIGN MASK LEVEL 1': 'Align the first lithography mask to the wafer using alignment marks.',
  'EXPOSE LITHO LEVEL 1': 'Expose the resist with the first pattern; monitor dose and focus.',
  'DEVELOP PHOTORESIST': 'Develop the exposed resist to reveal the intended feature pattern.',
  'PATTERN INSPECTION LEVEL 1': 'Inspect pattern fidelity, CD variation, and defect density.',
  'OXIDE ETCH': 'Etch oxide in the open regions with selectivity and endpoint control.',
  'STRIP PHOTORESIST': 'Remove remaining photoresist after etch.',
  'CLEAN AFTER ETCH': 'Clean post-etch residues and particles from the surface.',
  'MEASURE OPENING CD': 'Measure critical dimensions of etched openings and compare to target.',
  'IMPLANT WELL': 'Implant well dopants with defined dose, energy, and tilt.',
  'PRE ANNEAL CHECK': 'Check wafer condition and pattern integrity before anneal.',
  'DRIVE IN DIFFUSION': 'Drive dopants deeper into the substrate using a thermal diffusion step.',
  'RAPID THERMAL ANNEAL': 'Activate implanted dopants and repair crystal damage.',
  'MEASURE JUNCTION DEPTH': 'Measure junction depth and profile across wafer locations.',
  'GATE OXIDE PREP': 'Prepare the gate area with a final clean and surface conditioning.',
  'GATE OXIDE GROWTH': 'Grow a thin, high-quality gate oxide with tight thickness control.',
  'MEASURE GATE OXIDE THICKNESS': 'Measure gate oxide thickness and interface quality.',
  'DEPOSIT POLYSILICON': 'Deposit polysilicon gate material; monitor film thickness and uniformity.',
  'POLYSILICON ANNEAL': 'Anneal polysilicon to improve film properties and reduce stress.',
  'MEASURE POLY THICKNESS': 'Verify polysilicon thickness and across-wafer uniformity.',
  'ALIGN MASK LEVEL 2': 'Align the gate mask to the wafer and underlying structures.',
  'EXPOSE LITHO LEVEL 2': 'Expose the gate pattern using the second mask.',
  'POLY PATTERN INSPECTION': 'Inspect gate pattern for shorts, opens, and line-edge roughness.',
  'POLYSILICON ETCH': 'Etch the polysilicon gate using a directional dry etch.',
  'STRIP RESIST': 'Remove resist after poly etch.',
  'CLEAN AFTER POLY ETCH': 'Clean etch residues and prepare for source/drain formation.',
  'MEASURE GATE CD': 'Measure gate critical dimension and overlay accuracy.',
  'IMPLANT SOURCE DRAIN': 'Implant source/drain dopants with controlled dose and energy.',
  'LIGHT ANNEAL': 'Activate dopants and repair implant-induced damage.',
  'MEASURE SHEET RESISTANCE': 'Measure sheet resistance of source/drain regions to confirm activation.',
  'DEPOSIT SPACER DIELECTRIC': 'Deposit dielectric spacer material with controlled conformality.',
  'ANISOTROPIC ETCH SPACER': 'Etch spacer dielectric directionally to form sidewall spacers.',
  'MEASURE SPACER WIDTH': 'Measure spacer width and profile for process control.',
  'IMPLANT LDD': 'Perform lightly doped drain implant to reduce electric field concentration.',
  'MEASURE JUNCTION PROFILE': 'Verify dopant distribution and junction profile.',
  'DEPOSIT INTERLAYER DIELECTRIC': 'Deposit interlayer dielectric to isolate device layers and routing.',
  'DENSIFY DIELECTRIC': 'Densify dielectric by thermal treatment to improve film quality.',
  'MEASURE FILM THICKNESS': 'Measure dielectric thickness across wafer center and edge.',
  'CMP DIELECTRIC': 'Polish dielectric to achieve surface planarization.',
  'MEASURE PLANARITY': 'Measure surface planarity and residual topography after CMP.',
  'ALIGN MASK LEVEL 3': 'Align contact/via mask to underlying device features.',
  'EXPOSE LITHO LEVEL 3': 'Expose contact openings in the resist.',
  'VIA INSPECTION': 'Inspect via openings for CD, alignment, and completeness.',
  'VIA ETCH': 'Etch dielectric to open vias to the device layer.',
  'CLEAN AFTER VIA ETCH': 'Clean residues and prepare the surface for metallization.',
  'MEASURE VIA CD': 'Measure via critical dimension and verify target size.',
  'DEPOSIT BARRIER METAL': 'Deposit barrier layer to improve adhesion and prevent diffusion.',
  'DEPOSIT METAL SEED': 'Deposit seed layer for subsequent metal fill.',
  'FILL VIA METAL': 'Fill vias with metal, controlling voids and coverage.',
  'CMP METAL': 'Polish excess metal and leave filled contacts flush with the surface.',
  'MEASURE CONTACT RESISTANCE': 'Measure contact resistance to assess metallization quality.',
  'DEPOSIT METAL 1': 'Deposit first interconnect metal layer.',
  'ANNEAL METAL 1': 'Anneal metal layer to improve stability and reduce stress.',
  'ALIGN MASK LEVEL 4': 'Align metal routing mask.',
  'EXPOSE LITHO LEVEL 4': 'Expose the first metal routing pattern.',
  'METAL PATTERN INSPECTION': 'Inspect metal lines for opens, shorts, and CD variation.',
  'METAL ETCH': 'Etch the metal according to the routing pattern.',
  'CLEAN AFTER METAL ETCH': 'Clean residue and particles after etching.',
  'MEASURE LINE WIDTH': 'Measure line width and spacing.',
  'DEPOSIT PASSIVATION': 'Deposit passivation layer to protect the device from moisture and contamination.',
  'CURE PASSIVATION': 'Cure the passivation film to stabilize its properties.',
  'MEASURE PASSIVATION THICKNESS': 'Measure passivation thickness and coverage quality.',
  'OPEN PAD WINDOW': 'Open bond pad windows for probing and packaging.',
  'PAD WINDOW LITHO': 'Pattern resist for pad opening.',
  'PASSIVATION ETCH PAD OPENING': 'Etch the passivation layer at pad sites.',
  'CLEAN PAD OPENING': 'Clean pad area to ensure low-resistance electrical access.',
  'MEASURE PAD OPENING': 'Verify pad opening dimensions and completeness.',
  'FINAL CLEAN': 'Perform final clean before inspection and test.',
  'FINAL THICKNESS MEASURE': 'Measure final wafer thickness and mechanical state.',
  'FINAL GEOMETRY CHECK': 'Check bow, warp, and edge exclusion.',
  'FINAL PARTICLE INSPECTION': 'Perform final particle scan before electrical testing.',
  'PARAMETRIC TEST': 'Run electrical parametric tests on the completed wafer.',
  'THRESHOLD VOLTAGE TEST': 'Measure threshold voltage distribution across devices.',
  'LEAKAGE TEST': 'Check leakage current and isolate failing devices.',
  'SWITCHING TEST': 'Evaluate switching behavior and key device dynamics.',
  'WAFER SORT TEST': 'Sort wafers into bins according to electrical results.',
  'YIELD ANALYSIS': 'Analyze yield, defects, and any systematic process drift.',
  'LOT RELEASE': 'Release the lot after passing inspection and test criteria.',
  'SHIP LOT': 'Prepare and ship the lot to downstream packaging or customer.',
  'EPITAXY PREP': 'Prepare substrate surface for epitaxial growth with a final pre-clean.',
  'EPITAXIAL DEPOSITION': 'Grow the epitaxial silicon layer; control temperature, gas flow, and deposition rate.',
  'MEASURE EPITAXY THICKNESS': 'Measure epitaxial layer thickness and uniformity across the wafer.',
  'MEASURE RESISTIVITY': 'Measure resistivity or sheet resistance to confirm layer properties.',
  'EPITAXY ANNEAL': 'Anneal the epitaxial layer to improve crystal quality and reduce defects.',
  'IMPLANT P BODY': 'Implant p-type body region with controlled dose and energy.',
  'IMPLANT N BUFFER': 'Implant n-type buffer or field region for voltage support.',
  'DEPOSIT FIELD OXIDE': 'Deposit field oxide or dielectric for isolation and masking.',
  'DENSIFY OXIDE': 'Densify the oxide to improve film stability and quality.',
  'FIELD PATTERN INSPECTION': 'Inspect field or active-area pattern for defects and CDs.',
  'FIELD OXIDE ETCH': 'Etch oxide to open the defined area.',
  'CLEAN AFTER FIELD ETCH': 'Clean residues and particles from the etched surface.',
  'MEASURE SURFACE UNIFORMITY': 'Measure local surface uniformity after patterning.',
  'IMPLANT SOURCE REGION': 'Implant source/contact region dopants with defined energy and dose.',
  'IMPLANT DRAIN / CATHODE REGION': 'Implant the opposite contact region for diode or power-switch structure.',
  'DEPOSIT GATE OXIDE OR DIELECTRIC': 'Deposit a dielectric layer where needed for isolation or gate structure.',
  'ANNEAL DIELECTRIC': 'Anneal dielectric to improve film properties and reduce stress.',
  'MEASURE OXIDE QUALITY': 'Inspect dielectric quality, thickness, and defect density.',
  'POLYSILICON ETCH DRY': 'Etch polysilicon with directional dry etch.',
  'IMPLANT CHANNEL STOP': 'Implant channel-stop or termination regions to improve edge behavior.',
  'MEASURE DEVICE PARAMETER': 'Measure key device parameters after implant and anneal.',
  'MEASURE DIELECTRIC THICKNESS': 'Measure the dielectric thickness after deposition.',
  'CMP INTERLAYER DIELECTRIC': 'Polish the dielectric to achieve planarity.',
  'VIA ETCH THROUGH DIELECTRIC': 'Etch through dielectric to open contacts.',
  'DEPOSIT TOP METAL': 'Deposit top metal layer for interconnect or terminal formation.',
  'ANNEAL METAL': 'Anneal metal to improve grain structure and adhesion.',
  'MEASURE METAL THICKNESS': 'Measure metal thickness and uniformity.',
  'ALIGN MASK LEVEL 5': 'Align final metal mask.',
  'EXPOSE LITHO LEVEL 5': 'Expose resist for terminal or routing pattern.',
  'METAL ETCH DRY': 'Etch metal according to the designed layout.',
  'MEASURE PASSIVATION QUALITY': 'Check thickness, coverage, and defect density of the passivation.',
  'BACKSIDE GRIND': 'Thin the wafer backside to target thickness.',
  'BACKSIDE ETCH CLEAN': 'Remove grinding damage and backside residues.',
  'BACKSIDE RINSE': 'Rinse the backside to remove particles and etch byproducts.',
  'BACKSIDE DRY': 'Dry the wafer thoroughly after backside wet processing.',
  'BACKSIDE METALLIZATION PREP': 'Prepare backside for metal deposition and contact formation.',
  'DEPOSIT BACKSIDE METAL': 'Deposit backside metal for ohmic contact and thermal performance.',
  'BACKSIDE ANNEAL': 'Anneal backside metallization to improve adhesion and contact quality.',
  'MEASURE BACKSIDE CONTACT': 'Measure backside contact resistance and uniformity.',
  'ELECTRICAL PARAMETRIC TEST': 'Run device-level electrical tests on the completed wafer.',
  'BREAKDOWN VOLTAGE TEST': 'Test breakdown voltage to verify power robustness.',
  'WAFER SURFACE CLEAN': 'Remove particles and residues before thermal oxidation and lithography.',
  'BACKSIDE CLEAN': 'Clean the wafer backside to remove particles and residues.',
}

export function stepDescription(stepName: string): string | undefined {
  return STEP_DESCRIPTIONS[stepName.toUpperCase()] ?? STEP_DESCRIPTIONS[stepName]
}
